### PR TITLE
challenge-02

### PR DESCRIPTION
**Pull request by MaldoAlberto**
Proposed solution for challenge-02

### CODE REVIEW

**Comment by diemilio** [comment]
Hi @MaldoAlberto. Thank you very much for submitting your solution. I am going through your code, but I am having a bit of a hard time following what is happening on each step. Would it be possible for you to maybe add a short explanation before each of the steps you followed, and perhaps explicitly highlight:
1. What the sample input list looks like
2. What the expected outcome will be for that list
3. What the algorithm returned as an outcome

Thanks!

**Comment by MaldoAlberto** [comment]
Hello @diemilio I just made the modifications, I hope my answer is clearer, and an apologize for the lack of clarity.

**Comment by diemilio** [comment]
> Hello @diemilio I just made the modifications, I hope my answer is clearer, and an apologize for the lack of clarity.

Thanks @MaldoAlberto. It looks to me you are very close to a result. Any chance you can get the probability outputs to be actually representative of the options in the input list? What I mean by this is: take your example, it has four inputs ['0000','1001','1100','1101'], but the output probability distribution is giving a total of 16 solutions:
image

Any chance you can get your output to actually show only the four items from the list, where the two with the shortest distance are amplified? I know that your items are encoded in QRAM elements, so it would be OK if the output is just the binary position of the list items.

**Comment by MaldoAlberto** [comment]
I just modified my program where the output histograms are obtained where it only shows the outputs with minimum distance, for the input ['0000','0001','0010','0111'] it should be considered that

00 01 is equal to [0000,0001]

00 10 is equal to [0000,0010]

01 00 is equal to [0001,0000]

10 00 is equal to [0010,0000]

his_hamming


 00 01 is equal to  01 00 as is 00 10 equal to 10 00

**Comment by BillyLjm** [comment]
Hey @MaldoAlberto, do you mind explaining this section in your `hamming2()`  
```python
    qc.h(distance_h)
    qc.barrier()
    for i in distance_h:
        qc.cx(i,reg_oracle)
    qc.h(distance_h)
    qc.barrier()
    

    qc.x(distance_h[3])
    qc.mct(distance_h,reg_oracle)

    qc.x(distance_h[3])    
    qc.barrier()
    ...
```
If i understand correctly, this part intended to phase flip the component w/ minimum Hamming distance?
And that `distance_h` has the XOR of the bit string pairs at the start of that block?

Then you H it for some reason, flip conditioned on each individual bit be 1, then flip again conditioned on specific bis being 0?
I don't see how that picks out the component w/ minimum hamming distance

**Comment by MaldoAlberto** [comment]
**This part generated a qram where the input values are stored and it is done twice to be able to make the comparison between the value of array 0 with array 1 and so on.**


    qram(qc,address_1,distance_h,array)
    qram(qc,address_2,distance_h,array)

**This section used the idea of the Bernstein-Vazirani algorithm to find the Hamming distances**

    qc.h(distance_h)
    qc.barrier()
    for i in distance_h:
        qc.cx(i,reg_oracle)
    qc.h(distance_h)
    qc.barrier()
    
**This section is the necessary oracle for the minimum distance** 

    qc.x(distance_h[3])
    qc.mct(distance_h,reg_oracle)

    qc.x(distance_h[3])    
    qc.barrier()    

    qc.x(distance_h[0])

    qc.mct(distance_h,reg_oracle)
    qc.x(distance_h[0])
   
    qc.barrier() 
    
    qc.x(distance_h[2])
    qc.mct(distance_h,reg_oracle)
    qc.x(distance_h[2])
    qc.barrier()
    
    qc.x(distance_h[1])

    qc.mct(distance_h,reg_oracle)
    qc.x(distance_h[1])
   
    qc.barrier() 

   **This last part, I repeat the process to increase the probability of the oracle and follow the process that occurs in Grover's algorithm with the phase shift.**
    
    qc.h(distance_h)
    qc.barrier()
    for i in distance_h:
        qc.cx(i,reg_oracle)
    qc.h(distance_h)
    qc.barrier()
    
    qram(qc,address_2,distance_h,array)
    qram(qc,address_1,distance_h,array)
    qc.barrier() 


    qc.append(diffuser(2*n),[address_1[0],address_1[1],address_2[0],address_2[1]])
    qc.barrier() 
    qc.x(address_1)
    qc.x(address_2)
    qc.measure([address_1[0], address_1[1],address_2[0], address_2[1]], [c_1[0], c_1[1],c_2[0], c_2[1]])
    qc=qc.reverse_bits()
    return qc

**Comment by amirebrahimi** [comment]
Hi @MaldoAlberto, it looks like you have a duplicate file. Can you remove this one since it doesn't conform to the correct directory structure?
`maldoalberto-challenge-02/challenge-02.ipynb`

**Comment by MaldoAlberto** [comment]
@amirebrahimi  thank you very much for the observation, I already removed the duplicate

**Comment by Shiro-Raven** [comment]
Really nice and efficient approach! I have one question tho: In my understanding, you have assumed some initial value of minimum Hamming distance and then implemented the oracle accordingly. Is this correct? If so, how do you suggest we go around this if we don't want to impose an assumption on the distance beforehand?

**Comment by MaldoAlberto** [comment]
@Shiro-Raven  
Thank you very much and yes, you are right, I assumed the value of 1. When making the algorithm I realized that depending on the length of binary strings we can consider the possible distances and condition them in the oracle. 
For example, consider half the length of the string as a minimum distance and adder those possibilities in the oracle.

**Comment by peguerosdc** [comment]
Nice solution! One workaround I came up for considering multiple distances, was to chain various Grover algorithms (one per distance). That is, first you try to amplify **the** solution with a `distance=1`, then with a `distance=2` and so on. If the oracle doesn't find any state to amplify (that is, there is no state with the given distance), it will just scramble the states. If the oracle finds a solution (say, with distance=3), that state will be amplified and further rounds of amplification/scrambling to the next candidates (states with distance=4,5,etc) won't be enough to overcome the first amplification.
This works well when the amount of solutions is just one (i.e. there is only one pair of states `s1,s2` where `hamming(s1,s2)=min`) as the ideal amount of iterations `N` only depends on the length of each state/string, but when there is more than one solution, you need to know how many of them are to calculate `N` to make sure its amplification is strong enough to overcome the rest.
I haven't been able to come up with a workaround for my workaround, but maybe you guys have something in mind

**Comment by MaldoAlberto** [comment]
@peguerosdc 

For what I understood of your idea, I raised in each iteration to put each oracle, example first the conditions when distance = 1, then a second iteration distance = 2 with its conditions. This will give more probability if there is 1 equal to 1 and less solutions with distance 2, I share the histogram that came out of the example:

[1000, 1001, 0011, 1111]

distance between 1000 and 1001 = 1
indexes
[00 , 01] = [01, 00] 

distance between 10001 and 0011 = 2
indexes
[10 , 01] = [01,10] 

distance between 10001 and 0011 = 2
indexes
[10 , 01] = [01,10] 


distance between 1001 and 1111 = 2
indexes
[11 , 01] = [01,11] 


distance between 0011 and 1111 = 2
indexes
[11 , 10] = [10,11] 


the other cases their distance is 3, but in this example we are not interested.





output_40_0

**Pull request merged**
