### PR TITLE
challenge-02 solution

### PR DESCRIPTION
**Pull request by amirebrahimi**
This one took up quite a bit of my time! I wish I had figured out how to get quicker runs out of the qasm simulator earlier in the process 🤦‍♂️

### CODE REVIEW

**Comment by Shiro-Raven** [comment]
@amirebrahimi Can you elaborate more on getting the simulator to do runs faster? :sweat_smile: This sounds like something that could've been useful to me.

**Comment by amirebrahimi** [comment]
> @amirebrahimi Can you elaborate more on getting the simulator to do runs faster? 😅 This sounds like something that could've been useful to me.

Sure. Instead of using the default qasm simulator:
`backend = Aer.get_backend('qasm_simulator')`

Use single precision and optimization_level=3 when you run
```
backend = QasmSimulator(precision="single")
results = execute(qc, backend=backend, shots=shots, optimization_level=3).result()
```

**Comment by diemilio** [comment]
@amirebrahimi, very interesting approach. If you rerun the Grover portion of your circuit, will the probabilities of the values with the min Hamming distance keep increasing (just like in a conventional Grover circuit)?

**Comment by amirebrahimi** [comment]
> @amirebrahimi, very interesting approach. If you rerun the Grover portion of your circuit, will the probabilities of the values with the min Hamming distance keep increasing (just like in a conventional Grover circuit)?

The current iterations that are set are the optimal ones, so if I continued to run Grover's past those then the solution probability is reduced. It may look like it is dwarfed by "Others" because of how I chose to display the output, but they are the higher probabilities among the rest of the circuit.

**Pull request merged**
