### PR TITLE
July 2022 proposed solution

### PR DESCRIPTION
**Pull request by giorgosgiapis**
This is my proposed solution for the July 2022 palindromic integer challenge. This is my first time taking part in the challenge so I'm not so sure about my solution.

### CODE REVIEW

**Comment by MaldoAlberto** [comment]
Hi @giorgosgiapis  I hope you enjoy this challenge :grinning: , with respect your solution looks good,  could you  add a few lines of comments explaining what each part of your code ? 

you can add a few lines of comments explaining what each part of your code does 

after that you can accept your work as a solution :smile:

**Comment by giorgosgiapis** [comment]
Hi, @MaldoAlberto. Thanks for the review. I will add some comments explaining my solution and push my code  🙂

**Comment by MaldoAlberto** [comment]
Yes @giorgosgiapis , send me a message when you get them

**Comment by giorgosgiapis** [comment]
@MaldoAlberto I just finished writing them. Pushing now...

**Comment by MaldoAlberto** [comment]
@giorgosgiapis  looks good for me, I do the merge.

I hope you liked this challenge and look forward to the next ones, or if you have any suggestions and comments they are welcome.  :+1:

**Comment by giorgosgiapis** [comment]
@MaldoAlberto Thanks! It was a very fun challenge. Definitely looking forward to the next ones! 🙌

**Comment by pafloxy** [comment]
@giorgosgiapis Can I use one of the circuit diagrams from our solution notebook for one of my projects ? I agree to mention it explicitly that the source from which the image has been taken.

**Comment by giorgosgiapis** [comment]
@pafloxy Yeah, you can use any circuit diagram/code you want. I would appreciate it if you mentioned the source.

**Pull request merged**
