### PR TITLE
Shiro-Raven's challenge 2 submission

### PR DESCRIPTION
**Pull request by Shiro-Raven**

### CODE REVIEW

**Comment by amirebrahimi** [comment]
@Shiro-Raven - Great idea to use a comparator on qram memory addresses, which I figure is how you prevent duplicate permutations (e.g. ['1001', '1000'] and ['1000', '1001']) from being marked or am I misunderstanding?

**Comment by Shiro-Raven** [comment]
Yes, exactly! I thought I can use that as a way to augment the oracle, since we don't know the number of solutions beforehand.

**Comment by BillyLjm** [comment]
Iteratively upper-bounding the minimum distance is a really clever approach!
But I'm sceptcial that amplifying all states below the `currMinHam` could take non-scaling runtime???
Specifically, you used `IntegerComparator` from the library, which seems to hide the runtime

And I also realised that the adder and QRAM also take scaling runtime to implement.
Which I also used and overlooked in the runtime analysis of my own code

**Comment by Shiro-Raven** [comment]
Hmm yeah, you are raising some valid concerns there. I will go through each of them, but first, I suggest you go through this [paper](https://arxiv.org/pdf/quant-ph/9607014.pdf), since it was a main inspiration for my approach. So:

- Regarding the scaling runtime of the QRAM, I don't think it is a problem, since it's not the dominating element of the complexity of the algorithm. According to the paper, it takes logarithmic time in terms of the length of the search space.
- The adder scales up linearly with the number of qubits, but that's also not the dominating element, so no problems there. 
- The `IntegerComparator` is a fairly simple circuit, in my opinion. You can inspect its decomposition in the docs [here](https://www.qiskit.org/documentation/_modules/qiskit/circuit/library/arithmetic/integer_comparator.html).
- As to your point regarding the linearity of amplifying all states below the `currMinHam`, I think that the constraint I am applying to the value of the addresses (which results in an augmented oracle) somehow adds an upper bound to this amplification, which I believe is O(sqrt(N)), so we don't have to worry about this in our analysis of the complexity.

Please ask again or correct me if anything seems unclear/wrong. My knowledge of Quantum Algorithms Analysis is mediocre at best, but I tried my best to get this right :sweat_smile:  Thank you so much for the feedback! :smile:

**Comment by BillyLjm** [comment]
Maybe I'm misunderstanding your algorithm, but
The lower bounding of the distance (i.e. the classical iteration) occurs on average $\sim \log(n)$ times?
And within each of those iterations, you'd have to do Grover's algorithm for $n$ iterations (oracle & diffusion)?
But what if each individual oracle takes $O(n)$ runtime too; through the QRAM, adder, and/or phase flipping states one by one.
Then wouldn't the total runtime but $n^2 \log(n)$?

**Comment by Shiro-Raven** [comment]
Hmmm I think you are right there :sweat_smile:

**Pull request merged**
