### PR TITLE
Add challenge 08

### PR DESCRIPTION
**Pull request by amirebrahimi**
I've edited a few things and cleaned up the formatting. Have a quick review and if all looks good we'll make this live tomorrow.

### CODE REVIEW

**Review by Shiro-Raven — CHANGES_REQUESTED** [review]
The equations of the SWAP test are wrong. They should be fixed. The wikipedia page has the correct equations. 

There's also a typo in part 2 of the challenge --> "image image"

**Comment by amirebrahimi** [comment]
> The equations of the SWAP test are wrong. They should be fixed. The wikipedia page has the correct equations.
> 
> There's also a typo in part 2 of the challenge --> "image image"

Good catch. I didn't check any of those parts.

**Review by diemilio — APPROVED** [review]
Looks good. Thanks for taking the time to clean this up and make the final edits @amirebrahimi.

**Review by Shiro-Raven — CHANGES_REQUESTED** [review]
Thank you @amirebrahimi. The equation is still not accurate though. This is how it should be. In the notebook there's a square root around the 2 for some reason.
image

**Comment by amirebrahimi** [comment]
Thanks. Fixed @Shiro-Raven. I was focused mainly on there being two equations instead of one and missed that.

**Pull request merged**
