### PR TITLE
challenge-02 submission

### PR DESCRIPTION
**Pull request by BillyLjm**

### CODE REVIEW

**Comment by amirebrahimi** [comment]
A solid solution, @BillyLjm.

Can you share more about your qram implementation? I haven't seen it built with Rccx gates before. Is this an optimal way to create qram? Any related paper?

**Comment by BillyLjm** [comment]
Thank you @amirebrahimi :smile:
The qram is applying multi-controlled multi-traget (mcmt) gates from the address bits to the data bits.
It is based off qiskit's mcmt implementation, except that it uses rccx and minimises the uncomputation done specifically for the qram.

Based off [qiskit's documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.RCCXGate.html), the rccx saves some gates cost at the expense of an extra relative phase.
But the relative phase shouldn't make a difference in this case(?), since the the ancilla is used based on its 0/1 and not its phase; and the rccx is uncomputed and the phase reversed shortly after

**Comment by Shiro-Raven** [comment]
I think your solution is almost identical to me. Good job! I think you could have achieved a better complexity if you assumed pairs from the input and set your initial Hamming distance to that value. Then, find amplify the pairs whose Hamming Distance is less than that initial value. After that, pick one of those pairs randomly, and rerun the algorithm with their Hamming Distance. Repeat this until no more pairs with a smaller Hamming Distance gets amplified, so you terminate. According to my calculations, this has a complexity of n.log n for list of size n. Please check my solution and correct me if I am wrong about anything. Good job again. :smile:

**Comment by BillyLjm** [comment]
Yeah, your algorithm is similar to the quantum-classical algorithm I proposed!
(Although I ended up implementing a less general, fully-quantum one)
And your idea of starting from a upper bound from a random pair would indeed lower average runtime. I didn't think of that :smile:

**Comment by peguerosdc** [comment]
Very nice solution! I liked both of your approaches and the comparison between the complexities as functions of (n,m). Oh, and I learned about the RCCX trick, so that's definitely a plus 👍🏼

**Pull request merged**
