### PR TITLE
Solution 02 by peguerosdc

### PR DESCRIPTION
**Pull request by peguerosdc**
Hi!

This is my solution to challenge 2 using Grover's algorithm. Everything in the Jupyter notebook is commented, but feel free to ask any questions if needed.

Some caveats (or how I like to call it: "future work"):

- It is considered that the minimum Hamming distance to find is 1. How can this be extended to consider any arbitrary minimum distance?
- It is considered that we know in advance the amount of solutions to find so the amount of iterations can be calculated.

### CODE REVIEW

**Comment by peguerosdc** [comment]
I have updated my proposal so now we don't have to consider that the minimum Hamming distance is 1, but now we have to know the distances for every possible pair.
I don't feel it is necessarily an improvement as one constraint was removed to introduce another one, but I'd say it's just different 🙂

**Comment by diemilio** [comment]
Thank you @peguerosdc. I will look into your submission soon.

**Comment by amirebrahimi** [comment]
Thank you @peguerosdc for your solution. I like how you looked into how to iteratively amplify minimum hamming distances in increasing order. That was an open question I had in my solution.

I'm curious -- how long did this take to run?

**Comment by peguerosdc** [comment]
Thank you @amirebrahimi !

I am using IBM's online back-ends and for the first test case (4 digit strings with a total of 0+9+7+13=29 iterations) it takes 15.39 seconds. For the second test case with a considerably greater complexity (5 digit strings with a total of 0+25+18+18+25=86 iterations) it takes 6.03 minutes. Probably this would make the circuit impractical for some cases where N and k make the amount of iterations (~execution time) too large :confused:

**Pull request merged**
